apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: swapsphere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: swapsphere.azurecr.io/frontend:latest
        env:
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-configmap
              key: BACKEND_URL
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: swapsphere
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
